.SUFFIXES:
MAKEFLAGS += -r
SHELL := /bin/bash
_MK_DIR_THIS_MAKEFILE := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# INITIAL VARS
.DEFAULT_GOAL := help
_ENVMAKE_FILE_EXIST = 0

EARLYEXIT ?= 1
## CHECK SHELL SETUP
_MAKEFILE_KNOWN_SHELL := /bin/sh /bin/bash /usr/bin/tcsh /bin/zsh /home/linuxbrew/.linuxbrew/bin/nu
_MAKEFILE_DEFSHELL := $(SHELL)
#SHELL =
#SHELLFLAGS :=

_MAKEFILE_KNOWN_SHELL_NAME := $(strip $(foreach a,$(_MAKEFILE_KNOWN_SHELL),$(call notdir,$a)))

ifneq ("$(wildcard $(USESHELL))","")
ifneq ($(filter $(call notdir, $(USESHELL)),$(_MAKEFILE_KNOWN_SHELL_NAME)),)
#    $(info Current shell is: $(USESHELL) )
    SHELL = $(USESHELL)
else
    $(info Unknown shell: $(USESHELL); Use default: $(SHELL))
endif
endif

##
_MK_DIR_THIS_MAKEFILE := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

ifneq (,$(wildcard .envmake))
    _ENVMAKE_FILE_EXIST = 1
    include .envmake
else
    _ENVMAKE_FILE_EXIST = 0

    _SRV_AFFIX ?= .yml
    _VOL_AFFIX ?= .yml
    _ENV_AFFIX ?= .env

    _MK_DIR_MKFILE ?= .mkfile/
    _MK_DIR_TEST   ?= .test/
    _MK_DIR_TEMPLATE ?= .template/
    _MK_DIR_CONTEXT  ?= .context/
endif

_MK_DIR_TEST ?= .test/
_MK_FILE_KEYMAP ?= $(_MK_DIR_TEST)kv.db.txt
KEYMAP_FILES = $(_MK_FILE_KEYMAP)

## include ${_MK_DIR_THIS_MAKEFILE}/.mkfile/keymap.mk
## INCLUDE LIBRARY mk-files
_MK_FILE_NAME_INCLUDE_LIST := const.mk io.console.mk condition.mk keymap.mk context.mk service.mk help.mk
_MK_FILE_FULLNAME_INCLUDE_LIST := $(strip $(foreach m, $(_MK_FILE_NAME_INCLUDE_LIST), $(call addprefix, $(_MK_DIR_MKFILE), $m)))

include $(_MK_FILE_FULLNAME_INCLUDE_LIST)


.PHONY: all
test:
	@echo "_MK_FILE_KEYMAP :|$(_MK_FILE_KEYMAP)|"
	@printf "\n[keys list]\n"
	@echo "test            :|$(call keymap_key_list,test)|"
	@echo "url|subdir      :|$(call keymap_key_list,url|subdir)|"
	@printf "\n[empty value]\n"
	@echo "test            :|$(call keymap_val,test)|"
	@printf "\n[key sublevel]\n"
	@echo "test|key        :|$(call keymap_val,test|key)|"
	@echo "test|oneline    :|$(call keymap_val,test|oneline)|"
	@echo "test|multiline  :|$(call keymap_val,test|multiline)|"
	@printf "\n[key value]\n"
	@echo "testkv          :|$(call keymap_val,testkv)|"
	@printf "\n"
	@echo "url             :|$(call keymap_key_list,url)|"
	@echo "url|subdir      :|$(call keymap_val,url|subdir)|"
	@echo "url|subdir|slug :|$(call keymap_val,url|subdir|slug)|"
	@printf "\n"
	@echo "md5sum:|$(call keymap_val,md5sum)|"

testenv:
	
